from alpine:edge
label maintainer "zerosign <r1nlx0@gmail.com>"

env RUSTUP_TOOLCHAIN=nightly-x86_64-unknown-linux-musl

run echo '@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories && \
    apk add --no-cache cargo@testing rust@testing \
        curl ca-certificates gcc musl-dev make zlib-dev openssl-dev perl git

run curl https://sh.rustup.rs -sSf | sh

workdir /root
