[package]
name = "oracle"
version = "0.1.0"
authors = ["zerosign <r1nlx0@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.5.13"
tower-service = "0.1.0"
log = "0.4.5"
tokio = "0.1.8"
futures = "0.1.24"
rmp-serde = "0.13.5"
rmpv = "0.4.0"
